# Change these first
owner: sundowndev # Your GitHub username
repo: status # Your Github repository name

# Add your sites here
sites:
  - name: crvx.fr
    url: https://www.crvx.fr
  - name: PhoneInfoga demo instance
    url: https://demo.phoneinfoga.crvx.fr
  - name: Nextcloud instance
    url: $SECRET_SITE
  - name: Onlyoffice instance
    url: $SECRET_SITE_2
  - name: Dreamvo website
    url: https://dreamvo.com

status-website:
  # Add your custom domain below, or remove the next line if you don't have a domain
  # cname: demo.upptime.js.org
  # Uncomment the following line if you don't have a custom domain and add your repo name
  baseUrl: /status
  logoUrl: https://avatars.githubusercontent.com/u/16480203
  name: "Sundowndev's status page"
  introTitle: ""
  introMessage: This is a personal status page for the few web services I run in production.
  navbar:
    - title: Status
      href: /status
    - title: Github
      href: https://github.com/$OWNER/$REPO
    - title: Website
      href: https://crvx.fr/

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
