# Change these first
owner: sundowndev # Your GitHub username
repo: status # Your Github repository name

# Add your sites here
sites:
  - name: crvx.fr
    url: https://www.crvx.fr
  - name: PhoneInfoga demo instance
    url: https://demo.phoneinfoga.crvx.fr
  - name: Nextcloud instance
    url: $SECRET_SITE
  - name: Onlyoffice instance
    url: $SECRET_SITE_2

status-website:
  # Add your custom domain below, or remove the next line if you don't have a domain
  # cname: demo.upptime.js.org
  # Uncomment the following line if you don't have a custom domain and add your repo name
  baseUrl: /status
  logoUrl: https://raw.githubusercontent.com/sundowndev/website/4c0105bdd2afad35513211cebed1364f72750fd3/src/static/spy.svg
  name: "Sundowndev's status page"
  introTitle: ""
  introMessage: This is a personal status page for my infrastructure running few web services.
  navbar:
    - title: Status
      href: /status
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
